AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates ECR, roles, reserves Elastic IPs
Parameters:
  KeyName:
    Type: String
    Description: >
      Optional - Specifies the name of an existing Amazon EC2 key pair
      to enable SSH access to the EC2 instances in your cluster.
    Default: ''

# TODO: limit associate address to a certain namespace
Resources:
  AssociateAddressPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyDocument: 
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "ec2:AssociateAddress",
              "Resource": "*"
            }
          ]
        }
      PolicyName: !Join ["-", ["AssociateAddressPolicy", !Ref "AWS::Region"]]
      Roles:
        - !Ref ORBSNetworkRole

  ORBSNetworkRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        {
          "Version" : "2012-10-17",
          "Statement": [ {
            "Effect": "Allow",
            "Principal": {
                "Service": [ "ec2.amazonaws.com" ]
            },
            "Action": [ "sts:AssumeRole" ]
          } ]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy 
      RoleName: !Join ["-", ["orbs-network-role", !Ref "AWS::Region"]]

  ORBSNetworkInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref ORBSNetworkRole
      InstanceProfileName: !Join ["-", ["orbs-network-instance-profile", !Ref "AWS::Region"]]

  ORBSRepository:
    Type: "AWS::ECR::Repository"
    Properties: 
      RepositoryName: !Join ["-", ["orbs-network", !Ref "AWS::Region"]]

  ORBSNodeElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  # TODO: add condition, customize zone
  ORBSNodeDomainName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: orbs-test.com.
      Name: !Join [".", [!Ref "AWS::Region", "global.nodes.orbs-test.com."]]
      Type: A
      TTL: 900
      ResourceRecords:
        - !Ref ORBSNodeElasticIP

Outputs:
  ORBSNetworkRole:
    Value: !Ref ORBSNetworkRole
    Export:
      Name: !Join ["-", ["orbs-network-role", !Ref "AWS::Region"]]

  ORBSNetworkInstanceProfile:
    Value: !Ref ORBSNetworkInstanceProfile
    Export:
      Name: !Join ["-", ["orbs-network-instance-profile", !Ref "AWS::Region"]]

  ORBSRepository:
    Value: !Ref ORBSRepository
    Export:
      Name: !Join ["-", ["orbs-repository", !Ref "AWS::Region"]]

  ORBSNodeElasticIP:
    Value: !Ref ORBSNodeElasticIP
    Export:
      Name: !Join ["-", ["orbs-node-elastic-ip", !Ref "AWS::Region"]]

  ORBSNodeDomainName:
    Value: !Ref ORBSNodeDomainName
    Export:
      Name: !Join ["-", ["orbs-node-domain-name", !Ref "AWS::Region"]]

  TemplateVersion:
    Description: The version of the template used by ORBS
    Value: '1.0.0'
